### ISSUE TITLE
This Module doesnt appear to be useable for routing traffic through the firewall

### ISSUE THREAD

**Issue by jseiser** [terraform-aws-modules/terraform-aws-network-firewall#1]
## Is your request related to a new offering from AWS?
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
This module doesn't actually appear to be usable for routing traffic through the network firewall , when using this module for the vpc: https://github.com/terraform-aws-modules/terraform-aws-vpc

## Describe the solution you'd like.
The VPC module, and this module, should be able to create the firewall subnets, and handle the routing for the IGW to force traffic through the firewall

## Describe alternatives you've considered.
What we currently have to do with the normal VPC Module

1. Disable public subnets, and nat gateways
2. Create Public Subnets and NAT Gateway, and Internet Gateway
3. Create the route table for the NAT gateways
4. Create 2 Firewall Subnets and their route tables
5. Deploy this ( actually your old beta version) module passing in the firewall subnets in the subnet mapping
6. Create the routes for the IGW
7. Create the routes for the firewall subnets
8. Create all the route associations

## Additional context
My fear is this will eventually create a situation where we can no longer upgrade the main VPC module, since we have so much stuff disabled and manually created

**Comment by connellian** [comment]
Any update on this? It would be nice to have the routing and subnet associations added, as it is the complete example is not usable.

**Comment by bryantbiggs** [comment]
XRef https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/978#issuecomment-1721261248
